<?php 

class PostsTableSeeder extends DatabaseSeeder{

    public function run(){
        Post::create([
                    'title'         => 'First post title',
                    'content'       => "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Non modo carum sibi quemque, verum etiam vehementer carum esse? Varietates autem iniurasque fortunae facile veteres philosophorum praeceptis instituta vita superabat. Vulgo enim dicitur: Iucundi acti labores, nec male Euripidesconcludam, si potero, Latine; Duo Reges: constructio interrete. Nosti, credo, illud: Nemo pius est, qui pietatem-; </p><p>Idcirco enim non desideraret, quia, quod dolore caret, id in voluptate est. An hoc usque quaque, aliter in vita? Igitur ne dolorem quidem. Nunc agendum est subtilius. </p><p>Ut in voluptate sit, qui epuletur, in dolore, qui torqueatur. Quid, quod res alia tota est? Erit enim mecum, si tecum erit. Qua ex cognitione facilior facta est investigatio rerum occultissimarum. Iubet igitur nos Pythius Apollo noscere nosmet ipsos. Quis non odit sordidos, vanos, leves, futtiles? </p><p>Immo videri fortasse. Hoc ille tuus non vult omnibusque ex rebus voluptatem quasi mercedem exigit. Bona autem corporis huic sunt, quod posterius posui, similiora. Graece donan, Latine voluptatem vocant. Septem autem illi non suo, sed populorum suffragio omnium nominati sunt. Sic, et quidem diligentius saepiusque ista loquemur inter nos agemusque communiter. </p><p>Illum mallem levares, quo optimum atque humanissimum virum, Cn. Facile est hoc cernere in primis puerorum aetatulis. Hic ambiguo ludimur. Hic nihil fuit, quod quaereremus. Si verbum sequimur, primum longius verbum praepositum quam bonum. Sed haec omittamus; Egone quaeris, inquit, quid sentiam? Illum mallem levares, quo optimum atque humanissimum virum, Cn. Quod autem ratione actum est, id officium appellamus. </p>",
                    'is_premium'    => false
                ]);

        Post::create([
                    'title'         => 'Second post title',
                    'content'       => "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Non modo carum sibi quemque, verum etiam vehementer carum esse? Varietates autem iniurasque fortunae facile veteres philosophorum praeceptis instituta vita superabat. Vulgo enim dicitur: Iucundi acti labores, nec male Euripidesconcludam, si potero, Latine; Duo Reges: constructio interrete. Nosti, credo, illud: Nemo pius est, qui pietatem-; </p><p>Idcirco enim non desideraret, quia, quod dolore caret, id in voluptate est. An hoc usque quaque, aliter in vita? Igitur ne dolorem quidem. Nunc agendum est subtilius. </p><p>Ut in voluptate sit, qui epuletur, in dolore, qui torqueatur. Quid, quod res alia tota est? Erit enim mecum, si tecum erit. Qua ex cognitione facilior facta est investigatio rerum occultissimarum. Iubet igitur nos Pythius Apollo noscere nosmet ipsos. Quis non odit sordidos, vanos, leves, futtiles? </p><p>Immo videri fortasse. Hoc ille tuus non vult omnibusque ex rebus voluptatem quasi mercedem exigit. Bona autem corporis huic sunt, quod posterius posui, similiora. Graece donan, Latine voluptatem vocant. Septem autem illi non suo, sed populorum suffragio omnium nominati sunt. Sic, et quidem diligentius saepiusque ista loquemur inter nos agemusque communiter. </p><p>Illum mallem levares, quo optimum atque humanissimum virum, Cn. Facile est hoc cernere in primis puerorum aetatulis. Hic ambiguo ludimur. Hic nihil fuit, quod quaereremus. Si verbum sequimur, primum longius verbum praepositum quam bonum. Sed haec omittamus; Egone quaeris, inquit, quid sentiam? Illum mallem levares, quo optimum atque humanissimum virum, Cn. Quod autem ratione actum est, id officium appellamus. </p>",
                    'is_premium'    => true
                ]);
        Post::create([
                    'title'         => 'Third post title',
                    'content'       => "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Non modo carum sibi quemque, verum etiam vehementer carum esse? Varietates autem iniurasque fortunae facile veteres philosophorum praeceptis instituta vita superabat. Vulgo enim dicitur: Iucundi acti labores, nec male Euripidesconcludam, si potero, Latine; Duo Reges: constructio interrete. Nosti, credo, illud: Nemo pius est, qui pietatem-; </p><p>Idcirco enim non desideraret, quia, quod dolore caret, id in voluptate est. An hoc usque quaque, aliter in vita? Igitur ne dolorem quidem. Nunc agendum est subtilius. </p><p>Ut in voluptate sit, qui epuletur, in dolore, qui torqueatur. Quid, quod res alia tota est? Erit enim mecum, si tecum erit. Qua ex cognitione facilior facta est investigatio rerum occultissimarum. Iubet igitur nos Pythius Apollo noscere nosmet ipsos. Quis non odit sordidos, vanos, leves, futtiles? </p><p>Immo videri fortasse. Hoc ille tuus non vult omnibusque ex rebus voluptatem quasi mercedem exigit. Bona autem corporis huic sunt, quod posterius posui, similiora. Graece donan, Latine voluptatem vocant. Septem autem illi non suo, sed populorum suffragio omnium nominati sunt. Sic, et quidem diligentius saepiusque ista loquemur inter nos agemusque communiter. </p><p>Illum mallem levares, quo optimum atque humanissimum virum, Cn. Facile est hoc cernere in primis puerorum aetatulis. Hic ambiguo ludimur. Hic nihil fuit, quod quaereremus. Si verbum sequimur, primum longius verbum praepositum quam bonum. Sed haec omittamus; Egone quaeris, inquit, quid sentiam? Illum mallem levares, quo optimum atque humanissimum virum, Cn. Quod autem ratione actum est, id officium appellamus. </p>",
                    'is_premium'    => false
                ]);
    }//run
}//class